FROM haproxy:1.7

COPY haproxy.cfg /usr/local/etc/haproxy/haproxy.cfg

#docker cp haproxy.cfg haproxy:/usr/local/etc/haproxy/haproxy.cfg

#docker cp haproxy:/usr/local/etc/haproxy/haproxy.cfg haproxy.cfg 