from ubuntu:trusty
RUN apt-get -y update; \
    apt-get -y install apt-utils \
    vim \
    htop;
RUN apt-get -y install iperf
RUN apt-get -y install tcpdump
RUN apt-get -y install tshark
RUN apt-get -y install sysbench
CMD ["bash"]
